on:
  push:
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v2
        
      - name: Terraform Installation
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4
     
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  
            
      - name: Terraform fmt
        run: terraform fmt
        working-directory: .
        
          
      - name: Terraform validate
        run: terraform validate
        working-directory: .
        

      - name: Terraform plan
        run: |
          terraform plan \
            -var region="us-east-2" \
            -var access_key="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" 
        
      - name: Terraform apply
        run: |
          terraform apply -auto-approve \
            -var region="us-east-2" \
            -var access_key="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"  
